// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVrhq9fba0OT3zdpxZxfer43x_hRh-qE',
    appId: '1:593491112080:web:2f739598db01ce4664e815',
    messagingSenderId: '593491112080',
    projectId: 'wealth-accrue',
    authDomain: 'wealth-accrue.firebaseapp.com',
    storageBucket: 'wealth-accrue.appspot.com',
    measurementId: 'G-17YHVL42HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0LSBvQc00WuNayNgDlqWXwlW50ikcF0',
    appId: '1:593491112080:android:7c258c7ed78d28fe64e815',
    messagingSenderId: '593491112080',
    projectId: 'wealth-accrue',
    storageBucket: 'wealth-accrue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG0ih08yQ5RxOZ5rfZ7TwHiuES3LX7ltg',
    appId: '1:593491112080:ios:2580fc0b0fe0632f64e815',
    messagingSenderId: '593491112080',
    projectId: 'wealth-accrue',
    storageBucket: 'wealth-accrue.appspot.com',
    androidClientId: '593491112080-lc3jcta0f75e09120nuf4jb5ec7hti5v.apps.googleusercontent.com',
    iosClientId: '593491112080-l1busb5klvpmqiunkpo8rrpgi1fpd7k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG0ih08yQ5RxOZ5rfZ7TwHiuES3LX7ltg',
    appId: '1:593491112080:ios:2580fc0b0fe0632f64e815',
    messagingSenderId: '593491112080',
    projectId: 'wealth-accrue',
    storageBucket: 'wealth-accrue.appspot.com',
    androidClientId: '593491112080-lc3jcta0f75e09120nuf4jb5ec7hti5v.apps.googleusercontent.com',
    iosClientId: '593491112080-l1busb5klvpmqiunkpo8rrpgi1fpd7k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfile',
  );
}
